//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobWeb.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ApplyForJob
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public int Job_Id { get; set; }
        public string User_Id { get; set; }
        public System.DateTime ApplyDate { get; set; }
        [Required(ErrorMessage ="You Must Upload Your Cv Again")]
        public string File_Id { get; set; }
        public byte[] File_Content { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual JobDetail JobDetail { get; set; }
    }
}
