//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobWeb.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class JobDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobDetail()
        {
            this.ApplyForJobs = new HashSet<ApplyForJob>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage ="Job title required")]
        public string Job_title { get; set; }
        [Required(ErrorMessage = "Job title required")]
        public string Job_desc { get; set; }
        
        public string Image_Id { get; set; }

        public string User_Id { get; set; }
        public int Cat_Id { get; set; }
        public System.DateTime Creation_Date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplyForJob> ApplyForJobs { get; set; }
    }
}
